### ISSUE TITLE
How to migrate  k8s deployments from one namespace to another one?

### ISSUE THREAD

**Issue by mohamed-abdelrhman** [kotalco/api#9]
If i have a number of nodes under the default namespace for example , and since i can't rename namespaces .
how can i migrate these nodes from the current namespace to another one?

**Comment by mFarghaly** [comment]
You can rename the default workspace name, underlying Kubernetes namespace will be the same.

Unfortunately in Kubernetes you can't move resources from namespace to another, only way is to delete objects from first namespace, and recreate them in the second namespace.
